name: Format

on:
  push:
  pull_request:

jobs:
  build:
    name: Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Ruff Lint
        run: uv run ruff check --output-format=github .

      - name: Ruff Format
        run: uv run ruff format --check
